### ISSUE TITLE
Some Colab links may be broken

### ISSUE THREAD

**Issue by stared** [Machine-Learning-Tokyo/DL-workshop-series#4]
E.g. in https://github.com/Machine-Learning-Tokyo/DL-workshop-series/blob/master/Part%20I%20-%20Convolution%20Operations/ConvKernels.ipynb

> Notebook not found
There was an error loading this notebook. Ensure that the file is accessible and try again.
Ensure that you have permission to view this notebook in GitHub and authorize Colaboratory to use the GitHub API.
> 
> https://github.com/Machine-Learning-Tokyo/DL-workshop-series/blob/master/ConvKernels.ipynb

**Comment by suzana-ilic** [comment]
Hey there, could you check again? All links work on my side.
